language: node_js

node_js:
- 8.11.3

install:
- yarn


jobs:
  include: 
    - stage: test
      script: npm run test
    - stage: build
      script: npm run build
      on:
        tags: true
        repo: guoshencheng/JsonReact
    - stage: deplpy
      script: true
      deploy:
        provider: npm
        email: guoshencheng1@gmail.com
        api_key:
          secure: Bd27IiuD5LzzupB/b7h9D36RKNvHI6jQHNO81y9WM6wXiMYSrx84LsOqJUXcfdJ4XFFiZdCzok16W7gtTiXGa9rFZVwdm4fN2ssE/y+KNaE6mnJHQOIx8LJ6MBexHKr+uAy7aDD8chCEG9i2wxCkMAK3QjEQADivpBGwXTVrSNxW1tmrQVhbX3MzCTrEpAF8whPgQP3Isfw4mao2T5pg/eHrb60YOUEORaY/dyo86nthddK9+iEa1hlWEyYEISjkuFpvQ1k6GGRe0uHp6Be0H7h0fPpIVBNMkmIk4JBH92BuwdjY6EHXgM48cgVTqwrjRjBnU/IpdZPVTtle/3dGMpO0rF3V4RD6LdTvvVVjlKQOQbqmGFx0+2OJrZgnrlWCo+H0/uPyWb4fabxeNMyVZZl/NMp/ljfp3PEDNapILYKZVkuXflSfXMnpR/kNPjEGMHi0jOD71b0aeIpI5pz9UOmkiwZoRF7RgMwaI0ebzKezk1wSF1dT1pVS0wfhtT0U9rKLkan2UjoH2qdYbKZA/wwwEkGVbZwGj2UYwJMJ/g05voaWzKSZm2ZwDVoQNBsU6EtlGXww14JaUJdw/53CinCHFpmMKKUk3KZ7Uur6sAqKjF+1UKrR/OSJvBDgOgzi4ZVqanRuBJpSd+aF+9N3oUxPNJlM8piC4fToTZPKXOI=
        on:
          tags: true
          repo: guoshencheng/JsonReact